export const DEFAULT_ALLOW_ZOOM = true; // If enabled, the user will be able to manually zoom the camera
export const DEFAULT_ZOOM_SMOOTHNESS = 0.1; // The smoothness of the zoom
export const DEFAULT_MAX_ZOOM_IN = 10; // Represents the maximum amount the camera should zoom in
export const DEFAULT_MAX_ZOOM_OUT = 0.1; // Represents the maximum amount the camera should zoom out
export const DEFAULT_ALLOW_PAN = true; // If enabled, the user will be able to manually pan the camera.

export const INITIALIZE = "INITIALIZE";
export const ALLOW_PAN = "ALLOW_PAN";
export const DENY_PAN = "DENY_PAN";
export const PAN = "PAN";
export const PAN_BY = "PAN_BY";
export const RESET_PAN = "RESET_PAN";
export const CENTER = "CENTER";
export const ALLOW_ZOOM = "ALLOW_ZOOM";
export const DENY_ZOOM = "DENY_ZOOM";
export const ZOOM = "ZOOM";
export const ZOOM_FROM_WHEEL_EVENT = "ZOOM_FROM_WHEEL_EVENT";
export const RESET_ZOOM = "RESET_ZOOM";
export const RESET = "RESET_ZOOM";
