export const DEFAULT_ALLOW_ZOOM = true; // If enabled, the user will be able to manually zoom the camera
export const DEFAULT_ZOOM_SMOOTHNESS = 0.1; // The smoothness of the zoom
export const DEFAULT_MAX_ZOOM_IN = 10; // Represents the maximum amount the camera should zoom in
export const DEFAULT_MAX_ZOOM_OUT = 0.1; // Represents the maximum amount the camera should zoom out
export const DEFAULT_ALLOW_PAN = true; // If enabled, the user will be able to manually pan the camera.

export const INITIALIZE = "reviz/svg/INITIALIZE";
export const ALLOW_PAN = "reviz/svg/ALLOW_PAN";
export const DENY_PAN = "reviz/svg/DENY_PAN";
export const PAN = "reviz/svg/PAN";
export const PAN_BY = "reviz/svg/PAN_BY";
export const RESET_PAN = "reviz/svg/RESET_PAN";
export const CENTER = "reviz/svg/CENTER";
export const ALLOW_ZOOM = "reviz/svg/ALLOW_ZOOM";
export const DENY_ZOOM = "reviz/svg/DENY_ZOOM";
export const ZOOM = "reviz/svg/ZOOM";
export const ZOOM_FROM_WHEEL_EVENT = "reviz/svg/ZOOM_FROM_WHEEL_EVENT";
export const RESET_ZOOM = "reviz/svg/RESET_ZOOM";
export const RESET = "reviz/svg/RESET_ZOOM";
export const SET = "reviz/svg/SET";
